import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { Header } from "@/components/Header";
import { MswProvider } from "@/providers/MswProvider";
import { ReduxProvider } from "@/store/ReduxProvider";
import { ErrorBoundary } from "@/components/ErrorBoundary";
import { ErrorFallback } from "@/components/ErrorFallback";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <ErrorBoundary fallback={<ErrorFallback />}>
          <ReduxProvider>
            <Header/>
            <MswProvider>
              <QueryProvider>
                  {children}   
              </QueryProvider>
            </MswProvider>
          </ReduxProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}