import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/src/providers/QueryProvider";
import { Header } from "@/src/components/Header";
import { MswProvider } from "@/src/providers/MswProvider";
import { ReduxProvider } from "@/src/store/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <ReduxProvider>
          <Header/>
          <MswProvider>
            <QueryProvider>
                {children}   
            </QueryProvider>
          </MswProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
